# On every PR and main commit:
# - Build on GCC and Clang
# - Test on GCC

name: Make
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-build:
    strategy:
      matrix:
        compiler: [gcc, clang]
    runs-on:
      group: github-v1
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@1.69.0

      - uses: ./.github/actions/deps

      - name: Build everything
        run: make -j -Otarget

      - if: matrix.compiler == 'gcc'
        name: Run unit tests
        run: make -k -j4 -Otarget run-unit-test
