name: Make Test
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  make-test:
    runs-on: [self-hosted, Linux, X64, fedora28]
    defaults:
      run:
        shell: bash --noprofile --norc -eo pipefail -c "source /home/runner/firedancer-opts/activate-opt && ls -lah {0} && chmod +x {0} && {0}"
    env:
      EXTRAS: libbpf
    steps:
      - uses: actions/checkout@v3

      - name: Build everything
        run: make -j

      - name: Run unit tests
        run: make -kj --output-sync=target run-unit-test
